name:                conferer-provider-dhall
version:             0.1.0.1
synopsis: |
  Configuration for reading json files
description: |
  Library to abstract the parsing of many haskell config values from different config sources
homepage:            https://github.com/ludat/conferer#readme
license:             BSD3
author:              Lucas David Traverso
maintainer:          lucas6246@gmail.com
copyright:           MIT
category:            Configuration
license-file:        LICENSE

extra-doc-files:
  - README.md
  - LICENSE

dependencies:
  - base >= 4.3 && < 5
  - conferer == 0.1.0.1
  - conferer-provider-json == 0.1.0.1
  - bytestring >= 0.10 && < 0.11
  - text >= 1.1 && < 1.3
  - directory >= 1.2 && < 2.0
  - dhall >= 1.8 && < 2.0
  - dhall-json >= 1.0 && < 2.0

default-extensions:
  !include ../../utils/extensions.yaml

library:
  source-dirs: src

tests:
  conferer-provider-dhall-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - conferer-provider-dhall
    - hspec
