name:                conferer-warp
version:             0.2.0.0
synopsis: |
  conferer's FromConfig instances for warp settings
description: |
  Library to abstract the parsing of many haskell config values from different config sources
homepage:            https://github.com/ludat/conferer#readme
license:             BSD3
author:              Lucas David Traverso
maintainer:          lucas6246@gmail.com
copyright:           MIT
category:            Configuration
license-file:        LICENSE

extra-doc-files:
  - README.md
  - LICENSE

dependencies:
  - base >= 4.3 && < 5
  - conferer >= 0.1.0.1 && < 0.2.0.0
  - text >= 1.1 && < 1.3
  - warp >= 3.0 && < 4.0
  - wai >= 3.0 && < 4.0
  - http-types >= 0.8.6 && < 0.13

default-extensions:
  !include ../../utils/extensions.yaml

library:
  source-dirs: src

tests:
  conferer-warp-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - conferer-warp
    - hspec
