name:                example
version:             0.2.0.0
github:              "githubuser/example"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/example#readme>

dependencies:
- base >= 4.7 && < 5
- warp
- wai
- http-types
- conferer
- conferer-warp

default-extensions:
  !include ../utils/extensions.yaml

executables:
  example-exe:
    main:                Main.hs
    source-dirs:         app
