name: example
description: This is an example
author: Lucas David Traverso
maintainer: lucas6246@gmail.com

dependencies:
- base >= 4.7 && < 5
- warp
- wai
- http-types
- conferer
- conferer-warp

default-extensions:
  !include ../utils/extensions.yaml

executables:
  example-exe:
    main:                Main.hs
    source-dirs:         app
