language: generic

matrix:
  include:
  - env: RESOLVER=lts-11.20 # ghc 8.2
  - env: RESOLVER=lts-12.11 # ghc 8.4
  - env: RESOLVER=lts-14.18 # ghc 8.6
  - env: RESOLVER=nightly # nightly
  allow_failures:
  - env: RESOLVER=nightly # nightly

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

install:
  - mv -v -f "stack-${RESOLVER}.yaml" ./stack.yaml
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack --resolver="$RESOLVER" setup
  - stack --resolver="$RESOLVER" exec ghc -- --version
  - stack --resolver="$RESOLVER" build --test --only-dependencies

script:
  - stack --resolver="$RESOLVER" test
