language: generic

matrix:
  include:
  - env: STACK_YAML_VERSION="8.2"
  - env: STACK_YAML_VERSION="8.4"
  - env: STACK_YAML_VERSION="8.6"

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

install:
  - mv -v -f "stack-${STACK_YAML_VERSION}.yml" ./stack.yaml
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack setup
  - stack exec ghc -- --version
  - stack build --test --only-dependencies

script:
  - stack test
