language: haskell

matrix:
  include:
  - ghc: 8.6.5
    env: STACK_RESOLVER="lts-14.7"
  - ghc: 8.4.3
    env: STACK_RESOLVER="lts-12.11"
  - ghc: 8.2.2
    env: STACK_RESOLVER="lts-11.20"

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build --resolver "$STACK_RESOLVER" --system-ghc --test --bench --no-run-tests --no-run-benchmarks

script:
  - stack test --resolver "$STACK_RESOLVER" --system-ghc
