language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.2.2
    env: STACK_RESOLVER="ghc-8.2.2"
  - ghc: 8.4.4
    env: STACK_RESOLVER="ghc-8.4.4"
  - ghc: 8.6.5
    env: STACK_RESOLVER="ghc-8.6.5"

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build --resolver "$STACK_RESOLVER" --system-ghc --test --bench --no-run-tests --no-run-benchmarks

script:
  - stack test --resolver "$STACK_RESOLVER" --system-ghc
