language: haskell
ghc:
  - "8.6"
  - "8.4"
  - "8.2"
  - "8.0"
  - "7.10"
  - "7.8"
  - "7.6"
env:
  - PACKAGEDIR="conferer"
  - PACKAGEDIR="fetchFromConfig/warp"
  - PACKAGEDIR="fetchFromConfig/hspec"
  - PACKAGEDIR="fetchFromConfig/snap"
  - PACKAGEDIR="providers/dhall"
  - PACKAGEDIR="providers/yaml"
  - PACKAGEDIR="providers/json"


matrix:
  allow_failures:
    - ghc: "7.8"
    - ghc: "7.6"
before_install:
  - curl -sSL https://github.com/sol/hpack/raw/master/get-hpack.sh | bash
  - cd ${PACKAGEDIR}
  - hpack package.yaml

