language: haskell
ghc:
  - "8.6"
  - "8.4"
  - "8.2"
  - "8.0"
  - "7.10"
env:
  - PACKAGEDIR="conferer"
before_install:
  - curl -sSL https://github.com/sol/hpack/raw/master/get-hpack.sh | bash
  - cd ${PACKAGEDIR}
  - hpack package.yaml

