resolver: lts-13.24

packages:
  - ./conferer/
  - ./providers/json/
  - ./providers/yaml/
  - ./providers/dhall/

  - ./fetchFromConfig/warp/
  - ./fetchFromConfig/hspec/
  - ./fetchFromConfig/snap/
