resolver: lts-13.24
# resolver: lts-3.0

packages:
  - ./conferer/
  - ./example/
  - ./providers/json/
  - ./providers/yaml/
  - ./providers/dhall/

  - ./fetchFromConfig/warp/
  # - ./fetchFromConfig/hspec/
  - ./fetchFromConfig/snap/
