resolver: lts-16.2

packages:
  - ./conferer/
  - ./example/
  - ./sources/json/
  - ./sources/yaml/
  - ./sources/dhall/

  - ./fromConfig/warp/
  - ./fromConfig/hspec/
  - ./fromConfig/snap/
  - ./fromConfig/hedis/
