resolver: lts-13.24
packages:
  - ./conferer/
  - ./example/
  - ./providers/json/
  - ./providers/yaml/
  - ./providers/dhall/

  - ./fetchFromConfig/warp/
  # - ./fetchFromConfig/hspec/
  # - ./fetchFromConfig/snap/


ghc-options:
  "$locals": >
    -Wall
    -fno-warn-orphans
    -fno-warn-unused-do-bind
    -Wincomplete-record-updates
    -Wnoncanonical-monad-instances
    -Wnoncanonical-monadfail-instances
    -Wincomplete-uni-patterns
    -Widentities
    -Wcpp-undef
    -fhide-source-paths
    -Wno-missing-home-modules

