resolver: lts-16.12

packages:
  - ./packages/conferer/
  - ./packages/aeson/
  - ./packages/yaml/
  - ./packages/dhall/
  - ./packages/warp/
  - ./packages/hspec/
  - ./packages/snap/
  - ./packages/hedis/

  - ./example/
