name: conferer
version: 0.4.1.1
synopsis: |
  Configuration management library
description: |
  Library to abstract the parsing of many haskell config values from different config sources
homepage: https://conferer.ludat.io
author: Lucas David Traverso
maintainer: lucas6246@gmail.com
category: Configuration
license: MPL-2.0
license-file: LICENSE

extra-doc-files:
  - README.md
  - LICENSE

dependencies:
  - base >= 4.3 && < 5
  - containers >= 0.5 && < 0.7
  - bytestring >= 0.10 && < 0.11
  - text >= 1.1 && < 1.3
  - directory >= 1.2 && < 2.0

default-extensions:
  !include ../utils/extensions.yaml

library:
  source-dirs: src

tests:
  specs:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - conferer
      - hspec
      - deepseq

