name:                conferer
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ludat/conferer#readme
license:             BSD3
author:              Lucas David Traverso
maintainer:          lucas6246@gmail.com
copyright:           GPL3
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text
  - bytestring
  - directory

default-extensions:
  !include ../utils/extensions.yaml

library:
  source-dirs:      src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - conferer
      - hspec

