name: conferer-dhall
version: 0.4.0.1
synopsis: |
  Configuration for reading dhall files
description: |
  Library to abstract the parsing of many haskell config values from different config sources

_common/lib: !include ../../utils/package.common.yaml

<<: *everything

dependencies:
  - base >= 4.3 && < 5
  - conferer >= 0.4.0.0 && < 0.5.0.0
  - conferer-aeson >= 0.4.0.0 && < 0.5.0.0
  - bytestring >= 0.10 && < 0.11
  - text >= 1.1 && < 1.3
  - directory >= 1.2 && < 2.0
  - dhall >= 1.8 && < 2.0
  - dhall-json >= 1.0 && < 2.0

tests:
  specs:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - conferer-dhall
    - hspec
