name: conferer-snap
version: 0.4.0.1
synopsis: |
  conferer's FromConfig instances for snap Config
description: |
  Library to abstract the parsing of many haskell config values from different config sources

_common/lib: !include ../../utils/package.common.yaml

<<: *everything

dependencies:
  - base >= 4.3 && < 5
  - conferer >= 0.4.0.0 && < 0.5.0.0
  - text >= 1.1 && < 1.3
  - snap-server >= 1.0 && < 2.0
  - snap-core >= 1.0 && < 2.0

tests:
  specs:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - conferer-snap
    - hspec
