name: conferer-hedis
version: 1.0.0.0
synopsis: |
  conferer's FromConfig instances for hedis settings
description: |
  Library to abstract the parsing of many haskell config values from different config sources

_common/lib: !include ../../utils/package.common.yaml

<<: *everything

dependencies:
  - base >= 4.3 && < 5
  - conferer >= 1.0.0.0 && < 2.0.0.0
  - text >= 1.1 && < 1.3
  - hedis >= 0.7.0 && < 1.0.0

tests:
  specs:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - conferer-hedis
    - hspec
