name:                conferer-hspec
version:             0.1.0.1
synopsis: |
  Configuration for reading json files
description: |
  Library to abstract the parsing of many haskell config values from different config sources
homepage:            https://github.com/ludat/conferer#readme
license:             BSD3
author:              Lucas David Traverso
maintainer:          lucas6246@gmail.com
copyright:           MIT
category:            Configuration
license-file:        LICENSE

extra-doc-files:
  - README.md
  - LICENSE

dependencies:
  - base >= 4.7 && < 5
  # TODO fix dependencies


default-extensions:
  !include ../../utils/extensions.yaml

library:
  source-dirs: src

tests:
  conferer-hspec-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - conferer-hspec
    - hspec
