name:                conferer-snap
version:             0.1.0.0
synopsis: |
  Configuration for reading json files
description: |
  Library to abstract the parsing of many haskell config values from different config sources
homepage:            https://github.com/ludat/conferer#readme
license:             BSD3
author:              Lucas David Traverso
maintainer:          lucas6246@gmail.com
copyright:           MIT
category:            Configuration
license-file:        LICENSE

dependencies:
  - base >= 4.3 && < 5
  - conferer == 0.1.0.0
  - text >= 1.1 && < 1.3
  - snap-server >= 1.0 && < 2.0
  - snap-core >= 1.0 && < 2.0


default-extensions:
  !include ../../utils/extensions.yaml

library:
  source-dirs: src

tests:
  conferer-snap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conferer-snap
    - hspec
