name: Haskell CI

on: [push]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check version
      run: |
        curl -sSL https://get.haskellstack.org/ | sh
    - name: Install dependencies
      run: stack test --only-dependencies
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
