name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  push:
  schedule:
    - cron: '0 8 * * 3'

jobs:
  stack:
    name: ${{ matrix.os }} / ${{ matrix.snapshot }}
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.snapshot == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macOS, windows]
        snapshot:
          - 'lts-10.10'
          - 'lts-11.20'
          - 'lts-12.11'
          - 'lts-14.18'
          - 'lts-16.2'
          - 'nightly'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1.1.1
      name: Setup Haskell Stack
      with:
        enable-stack: true
        stack-version: latest

    - name: Get the stack root
      shell: bash
      run: |
        if [ -z "$STACK_ROOT" ]; then
          echo ::set-env name=STACK_ROOT::"$HOME/.stack"
        fi

    - uses: actions/cache@v1
      name: Cache STACK_ROOT
      with:
        path: ${{ env.STACK_ROOT }}
        key: ${{ runner.os }}-${{ matrix.snapshot }}-stack2

    - name: Setup stack.yaml
      shell: bash
      run: |
        mv -vf "stack-${{ matrix.snapshot }}.yaml" ./stack.yaml || true
        mv -vf "stack-${{ matrix.snapshot }}-${{ matrix.os }}.yaml" ./stack.yaml || true

    - name: Build and test
      shell: bash
      run: |
        if grep SKIP stack.yaml; then
          echo Skipped because that snapshot is broken
          exit 0
        fi
        stack setup --resolver=${{ matrix.snapshot }}
        echo stack_root: $STACK_ROOT
        stack --version
        stack --resolver=${{ matrix.snapshot }} ghc -- --version
        stack build -j 1 --resolver=${{ matrix.snapshot }} --test --bench --no-run-tests --no-run-benchmarks
        stack test -j 1 --resolver=${{ matrix.snapshot }}
